### ISSUE TITLE
Saving a picture

### ISSUE THREAD

**Issue by danvoell** [lfont/WebPaint#1]
This is a very cool app! I couldn't figure out how to get the save function to work. The error I get is:

Not Found

The requested URL /service/saveAs/drawing.png was not found on this server.

---

Sorry, I am fairly new to programming, I also had a  newbie question, where are the description variables defined? Like t.title & t.description?

**Comment by lfont** [comment]
Hi,

Does you run a local version of the app?
If you do, you must start the backend:

```
node app.js
```

There is [a hosted version of the app](http://lfont.webpaint.nodejitsu.com/) at nodejitsu.
I just check it and the "save" function works fine there.

Thanks for your feedback.

**Comment by danvoell** [comment]
Thanks for the quick response, I will try that. Thanks it worked. Sorry, I had never used node.js before.
